sudo: false
language: node_js
node_js:
  - "0.12"

before_install:
  - "curl https://install.meteor.com | /bin/sh"

script:
  - "~/.meteor/meteor test-packages --velocity --driver-package respondly:test-reporter ./"
